# server {
#     listen 80;

#     location /app/ {
#         proxy_pass http://react-frontend:80/;
#         proxy_set_header Host $host;
#     }

#     location /legacy/ {
#         proxy_pass http://apache-php:80/;
#         proxy_set_header Host $host;
#     }
# }


server {
    listen 80;

    location /app/ {
        rewrite ^/app/?(.*)$ /$1 break;
        proxy_pass http://react-frontend;
        proxy_set_header Host $host;
    }

    location /legacy/ {
        rewrite ^/legacy/?(.*)$ /$1 break;
        proxy_pass http://apache-php;
        proxy_set_header Host $host;
    }
}